### ISSUE TITLE
Gitleaks-Action v2 breaking update

### ISSUE THREAD

**Issue by weineran** [NEFSC/READ-SSB-Lee-RFAdataset#7]
Hello NEFSC,
We noticed that you are not pinning your gitleaks-action version, but rather [using gitleaks-action@master](https://github.com/NEFSC/READ-SSB-Lee-RFAdataset/blob/caf97ac9d178cf80aad366bc71949d8d44819a72/.github/workflows/secretScan.yml#L13). We wanted to give you a heads up that we are planning to merge gitleaks-action@v2 to master soon, which is a breaking update. See more details [here](https://github.com/gitleaks/gitleaks-action#-announcement). By the way, we think you'll love [v2's features](https://github.com/gitleaks/gitleaks-action#v2-benefits). Let us know if you have any questions!

Reference: https://github.com/NEFSC/READ-SSB-Lee-RFAdataset/blob/caf97ac9d178cf80aad366bc71949d8d44819a72/.github/workflows/secretScan.yml#L13

CC @mle2718 (I see you have contributed to this workflow)

**Comment by mle2718** [comment]
6bac539e6685f8d571edf9b038fc8e15fb76fdf8
